module.exports = {
    "DATABASE_ERROR": 1,
    "CREATE_TOKEN_ERROR": 2,
    "AUTHENTICATION_ERROR": 3,
    "INVALID_REQUEST": 4,
    "NOT_IMPLEMENTED": 5,
    "INVALID_TOKEN": 6,
    "ID_ALREADY_EXIST": 7,
    "RESOURCE_DELETED": 8,
    "RESOURCE_NOT_FOUNT": 9
};